name: Deploy Flask App to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Up Docker Buildx
        run: |
          docker buildx create --use

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 850995576645.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx build --platform=linux/arm64 -t 850995576645.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest . --push

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster flask-cluster --service new-service --force-new-deployment
